# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.setWindowModality(QtCore.Qt.NonModal)
        Login.setFixedSize(300, 200)
        Login.setWindowIcon(QIcon('njupt.ico'))
        Login.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(Login)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.School = QtWidgets.QRadioButton(self.centralwidget)
        self.School.setObjectName("School")
        self.verticalLayout_2.addWidget(self.School)
        self.ChinaNet = QtWidgets.QRadioButton(self.centralwidget)
        self.ChinaNet.setObjectName("ChinaNet")
        self.verticalLayout_2.addWidget(self.ChinaNet)
        self.CMCC = QtWidgets.QRadioButton(self.centralwidget)
        self.CMCC.setObjectName("CMCC")
        self.verticalLayout_2.addWidget(self.CMCC)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 2, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_username = QtWidgets.QLabel(self.centralwidget)
        self.label_username.setObjectName("label_username")
        self.horizontalLayout.addWidget(self.label_username)
        self.lineEdit_username = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.horizontalLayout.addWidget(self.lineEdit_username)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_passwd = QtWidgets.QLabel(self.centralwidget)
        self.label_passwd.setObjectName("label_passwd")
        self.horizontalLayout_2.addWidget(self.label_passwd)
        self.lineEdit_passed = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_passed.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_passed.setObjectName("lineEdit_passed")
        self.horizontalLayout_2.addWidget(self.lineEdit_passed)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 2)
        self.checkBox_savepasswd = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_savepasswd.setObjectName("checkBox_savepasswd")
        self.gridLayout.addWidget(self.checkBox_savepasswd, 1, 0, 1, 1)
        self.checkBox_selfstart = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_selfstart.setObjectName("checkBox_selfstart")
        self.gridLayout.addWidget(self.checkBox_selfstart, 3, 0, 1, 1)
        self.checkBox_autologin = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_autologin.setObjectName("checkBox_autologin")
        self.gridLayout.addWidget(self.checkBox_autologin, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_yes = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_yes.setObjectName("pushButton_yes")
        self.horizontalLayout_3.addWidget(self.pushButton_yes)
        self.pushButton_cancle = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cancle.setObjectName("pushButton_cancle")
        self.horizontalLayout_3.addWidget(self.pushButton_cancle)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 1, 2, 2)
        Login.setCentralWidget(self.centralwidget)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "南邮校园网自动登录"))
        self.School.setText(_translate("Login", "校园网"))
        self.ChinaNet.setText(_translate("Login", "中国电信"))
        self.CMCC.setText(_translate("Login", "中国移动"))
        self.label_username.setText(_translate("Login", "账号： "))
        self.label_passwd.setText(_translate("Login", "密码： "))
        self.checkBox_savepasswd.setText(_translate("Login", "保存密码"))
        self.checkBox_selfstart.setText(_translate("Login", "开机自启"))
        self.checkBox_autologin.setText(_translate("Login", "自动登录"))
        self.pushButton_yes.setText(_translate("Login", "确认登录"))
        self.pushButton_cancle.setText(_translate("Login", "取消"))
